// Generated by LizardGenFs
namespace Lizard.Protocol.ProtocolGen;

public interface ILizard1
{
    void Continue();
    LRegisters1 Break();
    LRegisters1 StepIn();
    LRegisters1 StepOver();
    LRegisters1 StepOut();
    LRegisters1 StepMultiple(uint cycles);
    void RunToAddress(LAddress1 address);
    LRegisters1 GetState();
    uint GetMaxNonEmptyAddress(ushort seg);
    List<LAddress1> SearchMemory(LAddress1 start, uint length, byte[] pattern, uint advance);
    List<LAssemblyLine1> Disassemble(LAddress1 address, uint length);
    byte[] GetMemory(LAddress1 address, uint length);
    void SetMemory(LAddress1 address, byte[] bytes);
    List<LBreakpoint1> ListBreakpoints();
    void SetBreakpoint(LBreakpoint1 breakpoint);
    void EnableBreakpoint(uint id, bool isEnabled);
    void DeleteBreakpoint(uint id);
    void SetRegister(LRegister1 reg, uint value);
    List<LDescriptor1> GetGdt();
    List<LDescriptor1> GetLdt();
}
