// Generated by LizardGenFs

using SerdesNet;

namespace Lizard.Protocol.ProtocolGen;

public class LAddress1
{
    public ushort Segment;
    public uint Offset;

    public static LAddress1 Serdes(SerdesName name, LAddress1? value, ISerdes s)
    {
        value ??= new LAddress1();
        s.Begin(name);
        value.Segment = s.UInt16(nameof(value.Segment), value.Segment);
        value.Offset = s.UInt32(nameof(value.Offset), value.Offset);
        s.End();
        return value;
    }
}
