// Generated by LizardGenFs

using SerdesNet;

namespace Lizard.Protocol.ProtocolGen;

public class LAssemblyLine1
{
    public LAddress1? Address;
    public string? Line;
    public byte[]? Bytes;

    public static LAssemblyLine1 Serdes(SerdesName name, LAssemblyLine1? value, ISerdes s)
    {
        value ??= new LAssemblyLine1();
        s.Begin(name);
        value.Address = LAddress1.Serdes(nameof(value.Address), value.Address, s);
        value.Line = s.String32Utf8(nameof(value.Line), value.Line);
        value.Bytes = s.Bytes32(nameof(value.Bytes), value.Bytes);
        s.End();
        return value;
    }
}
