// Generated by LizardGenFs

using SerdesNet;

namespace Lizard.Protocol.ProtocolGen;

public class LBreakpoint1
{
    public uint Id;
    public LAddress1? Address;
    public LBreakpointType1 Type;
    public byte IsEnabled;
    public byte Ah;
    public byte Al;

    public static LBreakpoint1 Serdes(SerdesName name, LBreakpoint1? value, ISerdes s)
    {
        value ??= new LBreakpoint1();
        s.Begin(name);
        value.Id = s.UInt32(nameof(value.Id), value.Id);
        value.Address = LAddress1.Serdes(nameof(value.Address), value.Address, s);
        value.Type = s.EnumU8(nameof(value.Type), value.Type);
        value.IsEnabled = s.UInt8(nameof(value.IsEnabled), value.IsEnabled);
        value.Ah = s.UInt8(nameof(value.Ah), value.Ah);
        value.Al = s.UInt8(nameof(value.Al), value.Al);
        s.End();
        return value;
    }
}
