// Generated by LizardGenFs

using SerdesNet;

namespace Lizard.Protocol.ProtocolGen;

public class LDescriptor1
{
    public LDescriptorType1 Type;
    public uint Offset;
    public uint Selector;
    public byte Dpl;
    public byte IsBig;

    public static LDescriptor1 Serdes(SerdesName name, LDescriptor1? value, ISerdes s)
    {
        value ??= new LDescriptor1();
        s.Begin(name);
        value.Type = s.EnumU8(nameof(value.Type), value.Type);
        value.Offset = s.UInt32(nameof(value.Offset), value.Offset);
        value.Selector = s.UInt32(nameof(value.Selector), value.Selector);
        value.Dpl = s.UInt8(nameof(value.Dpl), value.Dpl);
        value.IsBig = s.UInt8(nameof(value.IsBig), value.IsBig);
        s.End();
        return value;
    }
}
