// Generated by LizardGenFs

using SerdesNet;

namespace Lizard.Protocol.ProtocolGen;

public sealed class LizardClient1Serializer : ILizardClient1
{
    readonly PacketHandler _send;

    public LizardClient1Serializer(PacketHandler send)
    {
        _send = send ?? throw new ArgumentNullException(nameof(send));
    }

    static MemoryWriterSerdes Header(LizardClient1Message type)
    {
        MemoryWriterSerdes sw = new();
        sw.EnumU16(nameof(type), type);
        return sw;
    }

    public void Stopped(LRegisters1 state)
    {
        var sw = Header(LizardClient1Message.Stopped);
        LRegisters1.Serdes(nameof(state), state, sw);
        _ = new MemoryReaderSerdes(_send(sw.GetMemory()));
    }
}
