// Generated by LizardGenFs

using SerdesNet;

namespace Lizard.Protocol.ProtocolGen;

public class LRegisters1
{
    public uint Flags;
    public uint Eax;
    public uint Ebx;
    public uint Ecx;
    public uint Edx;
    public uint Esi;
    public uint Edi;
    public uint Ebp;
    public uint Esp;
    public uint Eip;
    public ushort Es;
    public ushort Cs;
    public ushort Ss;
    public ushort Ds;
    public ushort Fs;
    public ushort Gs;
    public byte IsStopped;

    public static LRegisters1 Serdes(SerdesName name, LRegisters1? value, ISerdes s)
    {
        value ??= new LRegisters1();
        s.Begin(name);
        value.Flags = s.UInt32(nameof(value.Flags), value.Flags);
        value.Eax = s.UInt32(nameof(value.Eax), value.Eax);
        value.Ebx = s.UInt32(nameof(value.Ebx), value.Ebx);
        value.Ecx = s.UInt32(nameof(value.Ecx), value.Ecx);
        value.Edx = s.UInt32(nameof(value.Edx), value.Edx);
        value.Esi = s.UInt32(nameof(value.Esi), value.Esi);
        value.Edi = s.UInt32(nameof(value.Edi), value.Edi);
        value.Ebp = s.UInt32(nameof(value.Ebp), value.Ebp);
        value.Esp = s.UInt32(nameof(value.Esp), value.Esp);
        value.Eip = s.UInt32(nameof(value.Eip), value.Eip);
        value.Es = s.UInt16(nameof(value.Es), value.Es);
        value.Cs = s.UInt16(nameof(value.Cs), value.Cs);
        value.Ss = s.UInt16(nameof(value.Ss), value.Ss);
        value.Ds = s.UInt16(nameof(value.Ds), value.Ds);
        value.Fs = s.UInt16(nameof(value.Fs), value.Fs);
        value.Gs = s.UInt16(nameof(value.Gs), value.Gs);
        value.IsStopped = s.UInt8(nameof(value.IsStopped), value.IsStopped);
        s.End();
        return value;
    }
}
