<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Icons\**" />
    <EmbeddedResource Remove="Icons\**" />
    <None Remove="Icons\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Gui\IconsDark\debug-continue.png" />
    <None Remove="Gui\IconsDark\debug-disconnect.png" />
    <None Remove="Gui\IconsDark\debug-pause.png" />
    <None Remove="Gui\IconsDark\debug-start.png" />
    <None Remove="Gui\IconsDark\debug-step-into.png" />
    <None Remove="Gui\IconsDark\debug-step-out.png" />
    <None Remove="Gui\IconsDark\debug-step-over.png" />
    <None Remove="Gui\IconsDark\debug-stop.png" />
    <None Remove="Gui\IconsDark\debug.png" />
    <None Remove="Gui\IconsDark\gear.png" />
    <None Remove="Gui\IconsLight\debug-continue.png" />
    <None Remove="Gui\IconsLight\debug-disconnect.png" />
    <None Remove="Gui\IconsLight\debug-pause.png" />
    <None Remove="Gui\IconsLight\debug-start.png" />
    <None Remove="Gui\IconsLight\debug-step-into.png" />
    <None Remove="Gui\IconsLight\debug-step-out.png" />
    <None Remove="Gui\IconsLight\debug-step-over.png" />
    <None Remove="Gui\IconsLight\debug-stop.png" />
    <None Remove="Gui\IconsLight\debug.png" />
    <None Remove="Gui\IconsLight\gear.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Gui\IconsDark\debug-continue.png" />
    <EmbeddedResource Include="Gui\IconsDark\debug-disconnect.png" />
    <EmbeddedResource Include="Gui\IconsDark\debug-pause.png" />
    <EmbeddedResource Include="Gui\IconsDark\debug-start.png" />
    <EmbeddedResource Include="Gui\IconsDark\debug-step-into.png" />
    <EmbeddedResource Include="Gui\IconsDark\debug-step-out.png" />
    <EmbeddedResource Include="Gui\IconsDark\debug-step-over.png" />
    <EmbeddedResource Include="Gui\IconsDark\debug-stop.png" />
    <EmbeddedResource Include="Gui\IconsDark\debug.png" />
    <EmbeddedResource Include="Gui\IconsDark\gear.png" />
    <EmbeddedResource Include="Gui\IconsLight\debug-continue.png" />
    <EmbeddedResource Include="Gui\IconsLight\debug-disconnect.png" />
    <EmbeddedResource Include="Gui\IconsLight\debug-pause.png" />
    <EmbeddedResource Include="Gui\IconsLight\debug-start.png" />
    <EmbeddedResource Include="Gui\IconsLight\debug-step-into.png" />
    <EmbeddedResource Include="Gui\IconsLight\debug-step-out.png" />
    <EmbeddedResource Include="Gui\IconsLight\debug-step-over.png" />
    <EmbeddedResource Include="Gui\IconsLight\debug-stop.png" />
    <EmbeddedResource Include="Gui\IconsLight\debug.png" />
    <EmbeddedResource Include="Gui\IconsLight\gear.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Gee.External.Capstone" Version="2.3.0" />
    <PackageReference Include="GhidraProgramData" Version="0.1.4" />
    <PackageReference Include="ImGuiColorTextEditNet" Version="0.1.9" />
    <PackageReference Include="SerdesNet" Version="4.1.0" />
    <PackageReference Include="Sinkers.Veldrid" Version="0.4.16" />
    <PackageReference Include="Sinkers.Veldrid.ImageSharp" Version="0.4.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lizard.Comms\Lizard.Comms.csproj" />
    <ProjectReference Include="..\SharpFileDialog\SharpFileDialog.csproj" />
  </ItemGroup>

</Project>
