open System.IO
open FParsec
open LizardGenFs.Parse
open LizardGenFs.Types
open LizardGenFs.TypeCheck
open LizardGenFs.Util

let loadLProto path =
    let parseLproto input =
        match run protocolFile input with
        | Success(result, _, _) -> result
        | Failure(msg, _, _) -> failwith msg

    let protoText = File.ReadAllText(path);
    let rawTypes = parseLproto protoText
    let checkedTypes = typecheck rawTypes
    reverseDependencyOrder checkedTypes

type CmdLineArg =
    | OutputDirectory of string
    | Namespace of string
    | GenerateCpp
    | GenerateCs
    | Verbose

let parseCmdLineArgs (args: string[]) : CmdLineArg list =
    let rec loop i acc =
        if i >= args.Length then List.rev acc else

        match args.[i] with
        | "-o"  when i + 1 < args.Length -> loop (i + 2) (OutputDirectory args.[i + 1]::acc)
        | "-ns" when i + 1 < args.Length -> loop (i + 2) (Namespace args.[i + 1]::acc)
        | "-cpp" -> loop (i + 1) (GenerateCpp::acc)
        | "-cs"  -> loop (i + 1) (GenerateCs::acc)
        | "-v"   -> loop (i + 1) (Verbose::acc)
        | unknown -> failwithf "Unknown or misplaced argument: %s" unknown

    loop 1 []

let writeFileIfDifferent fileName content isVerbose =
    if File.Exists fileName then
        let existingContent = File.ReadAllText(fileName)
        if existingContent = content then
            if isVerbose then
                printfn "Skipping %s (no changes)" fileName
        else
            printfn "Overwriting %s" fileName
            File.WriteAllText(fileName, content)
    else
        File.WriteAllText(fileName, content)
        printfn "Wrote %s" fileName

let generateCpp namespaceName types =
    [
        { name = $"{namespaceName}.g.h";   text = LizardGenFs.CppHeader.generateHeader       namespaceName types }
        { name = $"{namespaceName}.g.cpp"; text = LizardGenFs.CppImpl.generateImplementation namespaceName types }
    ]
    |> List.map (fun gf -> { gf with text =  "// Generated by LizardGenFs" + System.Environment.NewLine + gf.text })

[<EntryPoint>]
let main args =
    try
        // printfn "Running with \"%A\"" args
        if args.Length = 0 then
            printfn "Usage: LizardGenFs <lproto file> [-o OutputDirectory] [-cpp] [-cs]"
            printfn "-o: Specify output directory for generated files"
            printfn "-cpp: Generate C++ code"
            printfn "-cs: Generate C# code"
            printfn "-ns: Specify namespace"
            exit 1

        let path = args.[0]
        let options = parseCmdLineArgs args

        if not (File.Exists path) then
            printfn "File not found: %s" path
            exit 1

        let types = loadLProto path

        let destDir =
            let dir = options |> List.choose (function OutputDirectory dir -> Some dir | _ -> None)
            match dir with
            | [] -> Directory.GetCurrentDirectory()
            | [d] -> d
            | _ ->
                printfn "Multiple output directories specified"
                exit 1

        let namespaceName =
            options
            |> List.choose (function Namespace n -> Some n | _ -> None)
            |> List.tryHead
            |> Option.defaultValue (Path.GetFileNameWithoutExtension path)

        let isVerbose = options |> Seq.exists (fun x -> x = Verbose)
        Directory.CreateDirectory destDir |> ignore

        if (List.exists ((=) GenerateCpp) options) then
            printfn "LizardGensFs: Generating C++ code..."
            let cppResults = generateCpp namespaceName types
            for r in cppResults do
                let fileName = Path.Combine(destDir, r.name)
                writeFileIfDifferent fileName r.text isVerbose

        if (List.exists ((=) GenerateCs) options) then
            printfn "LizardGensFs: Generating C# code..."
            let csResults  = LizardGenFs.Cs.generate namespaceName types
            for r in csResults do
                let fileName = Path.Combine(destDir, r.name)
                writeFileIfDifferent fileName r.text isVerbose
        0
    with | ex -> printfn "Error: %s" (ex.ToString()); 1
