// Generated by LizardGenFs
#pragma once

#include <cstdint>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include "Serdes.h"

namespace LizardComms
{
    enum LogLevel { Debug, Info, Warn, Error, Fatal };
    class ILogger
    {
    public:
        virtual ~ILogger() = default;
        virtual void Debug(std::string_view message) = 0;
        virtual void Info(std::string_view message) = 0;
        virtual void Warn(std::string_view message) = 0;
        virtual void Error(std::string_view message) = 0;
        virtual void Fatal(std::string_view message) = 0;
    };

    class ISocket
    {
    public:
		virtual ~ISocket() = default;
        virtual ISocket* Accept() = 0;
		virtual void Send(std::span<const uint8_t> buffer) = 0;
		virtual void Receive(std::span<uint8_t> buffer) = 0;
        virtual void GetPeerAddress(uint32_t &ip, uint16_t& port) const = 0;
        virtual std::string GetPeerAddress() const = 0;
        virtual void Close() = 0;
    };

    class BitfieldEvent
    {
        int state_;
        std::mutex m_;
        std::condition_variable cv_;

    public:
        BitfieldEvent() : state_(false) {}
        void set(int flags)
        {
            std::unique_lock ul(m_);
            state_ |= flags;
            cv_.notify_all();
        }

        void clear(int flags)
        {
            std::unique_lock ul(m_);
            state_ &= ~flags;
        }

        int wait_any(int flags)
        {
            std::unique_lock ul(m_);
            while ((state_ & flags) == 0) {
                cv_.wait(ul);
            }

            return state_;
        }

        void wait_all(int flags)
        {
            std::unique_lock ul(m_);
            while ((state_ & flags) != flags) {
                cv_.wait(ul);
            }
        }

        int get(int flags) const
        {
            std::unique_lock ul(*const_cast<std::mutex*>(&m_));
            return state_ & flags;
        }
    };

    class ManualResetEvent
    {
        BitfieldEvent e_;

    public:
        void set() { e_.set(1); }
        void reset() { e_.clear(1); }
        void wait() { e_.wait_any(1); }
        bool get() const { return e_.get(1) != 0; }
    };

    uint8_t ClientHandshake(ISocket& socket, uint8_t maxClientVersion);
    uint8_t ServerHandshake(ISocket& socket, uint8_t maxServerVersion);

    class IDuplex
    {
    public:
        virtual ~IDuplex() = default;
        virtual void SendAndReplaceBufferWithResponse(std::vector<uint8_t>& buffer) = 0;
        virtual void WaitForExit() = 0;
        virtual void Disconnect() = 0;
    };

    IDuplex* CreateDuplex(
        std::unique_ptr<ISocket> socket,
        const std::shared_ptr<ILogger>& log,
        std::function<void(std::vector<uint8_t>&)> receiveAndReplaceBufferWithResponse);

    class IDeserializer
    {
    public:
        virtual ~IDeserializer() = default;
        virtual void HandleMessage(std::vector<uint8_t>& buffer) = 0;
    };

    class CommsError : public std::exception
    {
    public:
        explicit CommsError(const std::string& message) : std::exception(message.c_str()) {}
    };

    enum class LBreakpointType1 : uint8_t
    {
        Unknown = 0,
        Normal = 1,
        Ephemeral = 2,
        Read = 3,
        Write = 4,
        Interrupt = 5,
        InterruptWithAH = 6,
        InterruptWithAX = 7
    };

    enum class LDescriptorType1 : uint8_t
    {
        SysInvalid = 0,
        Sys286TssA = 1,
        SysLdt = 2,
        Sys286TssB = 3,
        Sys286CallGate = 4,
        SysTaskGate = 5,
        Sys286IntGate = 6,
        Sys286TrapGate = 7,
        Sys386TssA = 9,
        Sys386TssB = 11,
        Sys386CallGate = 12,
        Sys386IntGate = 14,
        Sys386TrapGate = 15,
        DataUpRead = 16,
        DataUpReadAcc = 17,
        DataUpWrite = 18,
        DataUpWriteAcc = 19,
        DataDnRead = 20,
        DataDnReadAcc = 21,
        DataDnWrite = 22,
        DataDnWriteAcc = 23,
        CodeAcc = 24,
        Code = 25,
        CodeReadAcc = 26,
        CodeRead = 27,
        CodeConfAcc = 28,
        CodeConf = 29,
        CodeReadConfAcc = 30,
        CodeReadConf = 31
    };

    enum class LRegister1 : uint8_t
    {
        Flags = 0,
        EAX = 1,
        EBX = 2,
        ECX = 3,
        EDX = 4,
        ESI = 5,
        EDI = 6,
        EBP = 7,
        ESP = 8,
        EIP = 9,
        ES = 10,
        CS = 11,
        SS = 12,
        DS = 13,
        FS = 14,
        GS = 15
    };

    struct LAddress1
    {
        uint16_t segment;
        uint32_t offset;

        template<typename Tname>
        void Serdes(Tname name, ISerdes& s)
        {
            s.Begin(name);
            s.UInt16("segment", segment);
            s.UInt32("offset", offset);
            s.End();
        }
    };

    struct LRegisters1
    {
        uint32_t flags;
        uint32_t eax;
        uint32_t ebx;
        uint32_t ecx;
        uint32_t edx;
        uint32_t esi;
        uint32_t edi;
        uint32_t ebp;
        uint32_t esp;
        uint32_t eip;
        uint16_t es;
        uint16_t cs;
        uint16_t ss;
        uint16_t ds;
        uint16_t fs;
        uint16_t gs;
        uint8_t is_stopped;

        template<typename Tname>
        void Serdes(Tname name, ISerdes& s)
        {
            s.Begin(name);
            s.UInt32("flags", flags);
            s.UInt32("eax", eax);
            s.UInt32("ebx", ebx);
            s.UInt32("ecx", ecx);
            s.UInt32("edx", edx);
            s.UInt32("esi", esi);
            s.UInt32("edi", edi);
            s.UInt32("ebp", ebp);
            s.UInt32("esp", esp);
            s.UInt32("eip", eip);
            s.UInt16("es", es);
            s.UInt16("cs", cs);
            s.UInt16("ss", ss);
            s.UInt16("ds", ds);
            s.UInt16("fs", fs);
            s.UInt16("gs", gs);
            s.UInt8("is_stopped", is_stopped);
            s.End();
        }
    };

    struct LAssemblyLine1
    {
        LAddress1 address;
        std::string line;
        std::vector<uint8_t> bytes;

        template<typename Tname>
        void Serdes(Tname name, ISerdes& s)
        {
            s.Begin(name);
            address.Serdes("address", s);
            s.String("line", line);
            s.Bytes("bytes", bytes);
            s.End();
        }
    };

    struct LBreakpoint1
    {
        uint32_t id;
        LAddress1 address;
        LBreakpointType1 type;
        uint8_t is_enabled;
        uint8_t ah;
        uint8_t al;

        template<typename Tname>
        void Serdes(Tname name, ISerdes& s)
        {
            s.Begin(name);
            s.UInt32("id", id);
            address.Serdes("address", s);
            s.UInt8Enum("type", type);
            s.UInt8("is_enabled", is_enabled);
            s.UInt8("ah", ah);
            s.UInt8("al", al);
            s.End();
        }
    };

    struct LDescriptor1
    {
        LDescriptorType1 type;
        uint32_t offset;
        uint32_t selector;
        uint8_t dpl;
        uint8_t is_big;

        template<typename Tname>
        void Serdes(Tname name, ISerdes& s)
        {
            s.Begin(name);
            s.UInt8Enum("type", type);
            s.UInt32("offset", offset);
            s.UInt32("selector", selector);
            s.UInt8("dpl", dpl);
            s.UInt8("is_big", is_big);
            s.End();
        }
    };

    class ILizardClient1
    {
    public:
        virtual ~ILizardClient1() = default;
        virtual void Stopped(LRegisters1& state) = 0;
    };

    IDeserializer* MakeLizardClient1Deserializer(ILizardClient1& receiver);
    ILizardClient1* MakeLizardClient1Serializer(std::function<void(std::vector<uint8_t>&)> sendCallback);

    class ILizard1
    {
    public:
        virtual ~ILizard1() = default;
        virtual void Continue() = 0;
        virtual LRegisters1 Break() = 0;
        virtual LRegisters1 StepIn() = 0;
        virtual LRegisters1 StepOver() = 0;
        virtual LRegisters1 StepOut() = 0;
        virtual LRegisters1 StepMultiple(uint32_t cycles) = 0;
        virtual void RunToAddress(LAddress1& address) = 0;
        virtual LRegisters1 GetState() = 0;
        virtual uint32_t GetMaxNonEmptyAddress(uint16_t seg) = 0;
        virtual std::vector<LAddress1> SearchMemory(LAddress1& start, uint32_t length, std::vector<uint8_t>& pattern, uint32_t advance) = 0;
        virtual std::vector<LAssemblyLine1> Disassemble(LAddress1& address, uint32_t length) = 0;
        virtual std::vector<uint8_t> GetMemory(LAddress1& address, uint32_t length) = 0;
        virtual void SetMemory(LAddress1& address, std::vector<uint8_t>& bytes) = 0;
        virtual std::vector<LBreakpoint1> ListBreakpoints() = 0;
        virtual void SetBreakpoint(LBreakpoint1& breakpoint) = 0;
        virtual void EnableBreakpoint(uint32_t id, bool is_enabled) = 0;
        virtual void DeleteBreakpoint(uint32_t id) = 0;
        virtual void SetRegister(LRegister1 reg, uint32_t value) = 0;
        virtual std::vector<LDescriptor1> GetGdt() = 0;
        virtual std::vector<LDescriptor1> GetLdt() = 0;
    };

    IDeserializer* MakeLizard1Deserializer(ILizard1& receiver);
    ILizard1* MakeLizard1Serializer(std::function<void(std::vector<uint8_t>&)> sendCallback);

}