// Generated by LizardGenFs
#include "LizardComms.g.h"
#include <cstdio>
#include <format>
#include <functional>
#include <future>
#include <span>

namespace LizardComms
{
    uint8_t ClientHandshake(ISocket& socket, uint8_t maxClientVersion)
    {
        const uint8_t buffer[] = { 'L', 'i', 'z', 'a', 'r', 'd', maxClientVersion };
        socket.Send(buffer);

        uint8_t maxServerVersion;
        socket.Receive(std::span(&maxServerVersion, 1));
        return std::min(maxClientVersion, maxServerVersion);
    }

    uint8_t ServerHandshake(ISocket& socket, uint8_t maxServerVersion)
    {
        static uint8_t HandshakeMagic[] = { 'L', 'i', 'z', 'a', 'r', 'd' /*, clientVersion*/ };
        uint8_t buffer[sizeof(HandshakeMagic) + 1] = {};

        socket.Receive(buffer);
        if (std::memcmp(buffer, HandshakeMagic, sizeof(HandshakeMagic)) != 0)
            throw CommsError("Invalid handshake received");

        uint8_t maxClientVersion = HandshakeMagic[sizeof(HandshakeMagic) - 1];
        uint8_t version = std::min(maxClientVersion, maxServerVersion);

        socket.Send(std::span(&maxServerVersion, 1));
        return version;
    }

    class BaseDeserializer
    {
    protected:
        void Respond(std::vector<uint8_t>& buffer) const
        {
            buffer.clear();
        }

        template<class T>
        void Respond(std::vector<uint8_t>& buffer, T& result)
        {
            buffer.clear();
            SerdesWrite sw(buffer);
            result.Serdes("result", sw);
        }

        template<class T>
        void Respond(std::vector<uint8_t>& buffer, std::vector<T>& results)
        {
            buffer.clear();
            SerdesWrite sw(buffer);
            uint32_t count = static_cast<uint32_t>(results.size());
            sw.UInt32("count", count);

            for (size_t i = 0; i < results.size(); i++)
            {
                T& result = results.at(i);
                result.Serdes(std::to_string(i), sw);
            }
        }

        template<>
        void Respond(std::vector<uint8_t>& buffer, std::vector<uint8_t>& results)
        {
            buffer.clear();
            SerdesWrite sw(buffer);
            sw.Bytes("result", results) ;
        }

        template<>
        void Respond(std::vector<uint8_t>& buffer, uint32_t& result)
        {
            buffer.clear();
            SerdesWrite sw(buffer);
            sw.UInt32("result", result);
        }
    };

    class BaseSerializer
    {
    protected:
        std::function<void(std::vector<uint8_t>&)> sendCallback_;

        explicit BaseSerializer(std::function<void(std::vector<uint8_t>&)> sendCallback)
            : sendCallback_(std::move(sendCallback))
        {
        }

        template<class T>
        std::vector<T> DecodeListResponse(std::span<uint8_t> response)
        {
            SerdesRead s(response);
            std::vector<T> results;
            s.Array("results", results);
            return results;
        }

        template<class T>
        T DecodeResponse(std::span<uint8_t> response)
        {
            SerdesRead s(response);
            T result;
            result.Serdes("result", s);
            return result;
        }

        template<>
        uint32_t DecodeResponse(std::span<uint8_t> response)
        {
            SerdesRead s(response);
            uint32_t result;
            s.UInt32("result", result);
            return result;
        }
    };

    class Duplex final : public IDuplex
    {
        static constexpr int MAX_CONCURRENCY = 16;

        enum class PacketType : uint8_t
        {
            Unknown = 0,
            Request = 1,
            ResponseOk = 2,
            ResponseFail = 3
        };

        const char* DescribePacketType(PacketType type)
        {
            switch (type)
            {
            case PacketType::Unknown: return "Unknown";
            case PacketType::Request: return "Request";
            case PacketType::ResponseOk: return "ResponseOk";
            case PacketType::ResponseFail: return "ResponseFail";
            default: return "Unknown";
            }
        }

        class Packet
        {
            std::vector<uint8_t> ownedData;

        public:
            PacketType type;
            uint8_t id;
            std::vector<uint8_t>& data;
            ManualResetEvent done;

            Packet(PacketType typeParam, uint8_t idParam) :
                type(typeParam),
                id(idParam),
                data(ownedData)
            {
            }

            Packet(PacketType typeParam, uint8_t idParam, std::vector<uint8_t>& dataParam) :
                type(typeParam),
                id(idParam),
                data(dataParam)
            {
            }

            Packet(const Packet&) = delete;
            Packet& operator=(const Packet&) = delete;
            ~Packet() = default;
        };

        class DuplexEvents
        {
            enum EventFlags
            {
                Done = 1 << 0,
                SendQueue = 1 << 1,
                ReceiveQueue = 1 << 2,
            };

            BitfieldEvent e_;

        public:
            void SetDone() { e_.set(Done); }
            void SendQueueAvailable() { e_.set(SendQueue); }
            void SendQueueCleared() { e_.clear(SendQueue); }
            void WaitUntilDone() { e_.wait_any(Done); }
            bool IsDone() const { return e_.get(Done) != 0; }

            int WaitForSendOrDone() // Return 0 if done
            {
                int result = e_.wait_any(Done | SendQueue);
                return result & Done ? 0 : 1;
            }
        };

        std::unique_ptr<ISocket> socket_;
        DuplexEvents events_;
        std::mutex mutex_;
        std::list<uint8_t> freeIds_;
        std::shared_ptr<ILogger> log_;
        std::list<std::shared_ptr<Packet> > sendQueue_;
        std::list<std::shared_ptr<Packet> > pendingRequests_;
        std::list<std::shared_ptr<Packet> > receiveQueue_;
        std::unique_ptr<std::thread>        sendThread_;
        std::unique_ptr<std::thread>        receiveThread_;
        std::function<void(std::vector<uint8_t>&)> receiveFunc_;

        // Must be called with mutex_ held
        bool TryGetId(uint8_t& id)
        {
            if (freeIds_.empty())
                return false;

            id = freeIds_.front();
            freeIds_.pop_front();
            return true;
        }

        // Must be called with mutex_ held
        void ReturnId(uint8_t id) { freeIds_.push_back(id); }

        void SendLoop()
        {
            while (events_.WaitForSendOrDone()) // Returns 0 when done
            {
                std::shared_ptr<Packet> packet = TryPopSendQueue();
                if (packet == nullptr)
                    continue;

                if (!SendPacket(*packet))
                {
                    events_.SetDone();
                    break;
                }

                if (packet->type == PacketType::Request)
                {
                    std::unique_lock lock(mutex_);
                    pendingRequests_.emplace_back(packet);
                }
                else
                {
                    packet->done.set();
                }
            }

            log_->Debug("Exiting Duplex::SendLoop");
        }

        std::shared_ptr<Packet> TryPopSendQueue()
        {
            std::unique_lock lock(mutex_);
            if (sendQueue_.empty())
            {
                events_.SendQueueCleared();
                return nullptr;
            }

            std::shared_ptr<Packet> packet = sendQueue_.front();
            sendQueue_.pop_front();
            return packet;
        }

        void ReceiveLoop()
        {
            while (!events_.IsDone())
            {
                try
                {
                    if (!ReceivePacket())
                        events_.SetDone();
                }
                catch (const CommsError&)
                {
                    events_.SetDone();
                }
            }

            log_->Debug("Exiting Duplex::ReceiveLoop");
        }

        bool SendPacket(Packet& packet)
        {
            std::vector<uint8_t> header;
            header.reserve(6);

            SerdesWrite sw(header);
            uint32_t size = packet.data.size();
            sw.UInt32("size", size);
            sw.UInt8Enum("type", packet.type);
            sw.UInt8("id", packet.id);
            log_->Info(std::format("SEND {} {} - {} bytes", (int)packet.id, DescribePacketType(packet.type), (int)size));

            socket_->Send(header);
            socket_->Send(packet.data);
            return true;
        }

        bool ReceivePacket()
        {
            uint8_t header[6];
            socket_->Receive(header);

            uint32_t size = 0;
            PacketType type = PacketType::Request;
            uint8_t id = 0;

            SerdesRead sr(std::span(header, sizeof(header)));
            sr.UInt32("size", size);
            sr.UInt8Enum("type", type);
            sr.UInt8("id", id);

            std::shared_ptr<Packet> packet;
            {
                std::unique_lock lock(mutex_);
                if (type == PacketType::ResponseOk || type == PacketType::ResponseFail)
                {
                    auto it = std::ranges::find_if(pendingRequests_,
                        [id](const std::shared_ptr<Packet>& p) { return p->id == id; });

                    if (it == pendingRequests_.end())
                    {
                        log_->Error(std::format("Duplex::ReceivePacket: Received response with unknown id {}", id));
                        return false;
                    }

                    packet = *it;
                    packet->type = type;
                    pendingRequests_.erase(it);
                }
                else if (type == PacketType::Request)
                {
                    packet = std::make_shared<Packet>(type, id);
                }
                else
                {
                    log_->Error(std::format("Duplex::ReceivePacket: Received unexpected packet type {}", static_cast<int>(type)));
                    return false;
                }
            }

            packet->data.resize(size);
            log_->Info(std::format("RECV {} {} - {} bytes", (int)id, DescribePacketType(type), (int)size));
            socket_->Receive(packet->data);

            if (type == PacketType::ResponseOk || type == PacketType::ResponseFail)
            {
                // Set the event to unblock the synchronous sender so it can decode and handle the response.
                packet->done.set();
            }
            else if (type == PacketType::Request)
            {
                auto future = std::async(
                    std::launch::async,
                    &Duplex::HandleIncomingRequest,
                    this,
                    packet);
            }
            else
            {
                log_->Warn(std::format("Duplex::ReceivePacket: Unexpected packet type \"{}\" received", (int)type));
            }

            return true;
        }

        void HandleIncomingRequest(std::shared_ptr<Packet> packet)
        {
            if (packet == nullptr)
                return;

            try
            {
                receiveFunc_(packet->data);
                packet->type = PacketType::ResponseOk;
            }
            catch (const std::exception& ex)
            {
                std::string msg = ex.what();
                packet->data.clear();
                packet->data.insert(packet->data.end(), msg.begin(), msg.end());
                packet->type = PacketType::ResponseFail;
            }

            {
                std::unique_lock lock(mutex_);
                EnqueueForSend(packet);
            }
        }

        void EnqueueForSend(std::shared_ptr<Packet> packet)
        {
            sendQueue_.emplace_back(packet);
            events_.SendQueueAvailable();
        }

    public:
        Duplex(
            std::unique_ptr<ISocket> socket,
            const std::shared_ptr<ILogger>& log,
            std::function<void(std::vector<uint8_t>&)> receiveAndReplaceBufferWithResponse
        ) :
            socket_(std::move(socket)),
            log_(log),
            receiveFunc_(std::move(receiveAndReplaceBufferWithResponse))
        {
            sendThread_ = std::make_unique<std::thread>(&Duplex::SendLoop, this);
            receiveThread_ = std::make_unique<std::thread>(&Duplex::ReceiveLoop, this);

            for (uint8_t i = 0; i < MAX_CONCURRENCY; i++)
                freeIds_.push_back(i);
        }

        ~Duplex() override
        {
            events_.SetDone();
            sendThread_->join();
            receiveThread_->join();
        }

        void WaitForExit() override { events_.WaitUntilDone(); }
        void Disconnect() override
        {
            socket_->Close();
            events_.SetDone();
        }

        void SendAndReplaceBufferWithResponse(std::vector<uint8_t>& buffer) override
        {
            // Outbound packet lifecycle:
            // 1. Created and added to sendQueue
            // 2. Moved to pendingRequests when sent
            // 3. Removed from pendingRequests when response received, buffer contents replaced and event set
            // 4. Destroyed when going out of scope after Send returns
            std::shared_ptr<Packet> packet;
            {
                std::unique_lock lock(mutex_);
                uint8_t id;
                if (!TryGetId(id))
                    throw CommsError("Maximum concurrency reached");

                packet = std::make_shared<Packet>(PacketType::Request, id, buffer);
                EnqueueForSend(packet);
            }

            packet->done.wait();

            ReturnId(packet->id);

            if (packet->type == PacketType::ResponseFail)
                throw CommsError(std::string(packet->data.begin(), packet->data.end()));
        }
    };

    IDuplex* CreateDuplex(std::unique_ptr<ISocket> socket, const std::shared_ptr<ILogger>& log, std::function<void(std::vector<uint8_t>&)> receive)
    {
        return new Duplex(std::move(socket), log, std::move(receive));
    }

    enum class LizardClient1Message : uint16_t
    {
        Unknown = 0,
        Stopped = 1
    };

    class LizardClient1Deserializer final : public IDeserializer, BaseDeserializer
    {
        ILizardClient1& receiver_;

    public:
        explicit LizardClient1Deserializer(ILizardClient1& receiver) : receiver_(receiver) {}
        void HandleMessage(std::vector<uint8_t>& buffer) override
        {
            if (buffer.empty())
                throw CommsError("Insufficient data for LizardClient1 deserialization");

            SerdesRead sr(buffer);
            LizardClient1Message messageType = LizardClient1Message::Unknown;
            sr.UInt16Enum("type", messageType);

            switch (messageType)
            {
                case LizardClient1Message::Unknown:
                    throw CommsError("Unknown message type received in LizardClient1 deserializer");

                case LizardClient1Message::Stopped:
                {
                    LRegisters1 state;
                    state.Serdes("state", sr);
                    receiver_.Stopped(state);
                    Respond(buffer);
                    break;
                }
            }

#ifdef _DEBUG
            if (sr.BytesRemaining() != 0)
                throw CommsError("Unexpected data remaining after processing LizardClient1 message");
#endif
        }
    };

    IDeserializer* MakeLizardClient1Deserializer(ILizardClient1& receiver) { return new LizardClient1Deserializer(receiver); }

    class LizardClient1Serializer final : public ILizardClient1, BaseSerializer
    {
    public:
        explicit LizardClient1Serializer(std::function<void(std::vector<uint8_t>&)> sendCallback)
            : BaseSerializer(std::move(sendCallback))
        {
        }

        void Stopped(LRegisters1& state) override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            LizardClient1Message type = LizardClient1Message::Stopped;

            sw.UInt16Enum("type", type);
            state.Serdes("state", sw);
            sendCallback_(buffer);
        }
    };

    ILizardClient1* MakeLizardClient1Serializer(std::function<void(std::vector<uint8_t>&)> sendCallback)
    {
        return new LizardClient1Serializer(std::move(sendCallback));
    }

    enum class Lizard1Message : uint16_t
    {
        Unknown = 0,
        Continue = 1,
        Break = 2,
        StepIn = 3,
        StepOver = 4,
        StepOut = 5,
        StepMultiple = 6,
        RunToAddress = 7,
        GetState = 8,
        GetMaxNonEmptyAddress = 9,
        SearchMemory = 10,
        Disassemble = 11,
        GetMemory = 12,
        SetMemory = 13,
        ListBreakpoints = 14,
        SetBreakpoint = 15,
        EnableBreakpoint = 16,
        DeleteBreakpoint = 17,
        SetRegister = 18,
        GetGdt = 19,
        GetLdt = 20
    };

    class Lizard1Deserializer final : public IDeserializer, BaseDeserializer
    {
        ILizard1& receiver_;

    public:
        explicit Lizard1Deserializer(ILizard1& receiver) : receiver_(receiver) {}
        void HandleMessage(std::vector<uint8_t>& buffer) override
        {
            if (buffer.empty())
                throw CommsError("Insufficient data for Lizard1 deserialization");

            SerdesRead sr(buffer);
            Lizard1Message messageType = Lizard1Message::Unknown;
            sr.UInt16Enum("type", messageType);

            switch (messageType)
            {
                case Lizard1Message::Unknown:
                    throw CommsError("Unknown message type received in Lizard1 deserializer");

                case Lizard1Message::Continue:
                {
                    receiver_.Continue();
                    Respond(buffer);
                    break;
                }

                case Lizard1Message::Break:
                {
                    LRegisters1 result = receiver_.Break();
                    Respond(buffer, result);
                    break;
                }

                case Lizard1Message::StepIn:
                {
                    LRegisters1 result = receiver_.StepIn();
                    Respond(buffer, result);
                    break;
                }

                case Lizard1Message::StepOver:
                {
                    LRegisters1 result = receiver_.StepOver();
                    Respond(buffer, result);
                    break;
                }

                case Lizard1Message::StepOut:
                {
                    LRegisters1 result = receiver_.StepOut();
                    Respond(buffer, result);
                    break;
                }

                case Lizard1Message::StepMultiple:
                {
                    uint32_t cycles;
                    sr.UInt32("cycles", cycles);
                    LRegisters1 result = receiver_.StepMultiple(cycles);
                    Respond(buffer, result);
                    break;
                }

                case Lizard1Message::RunToAddress:
                {
                    LAddress1 address;
                    address.Serdes("address", sr);
                    receiver_.RunToAddress(address);
                    Respond(buffer);
                    break;
                }

                case Lizard1Message::GetState:
                {
                    LRegisters1 result = receiver_.GetState();
                    Respond(buffer, result);
                    break;
                }

                case Lizard1Message::GetMaxNonEmptyAddress:
                {
                    uint16_t seg;
                    sr.UInt16("seg", seg);
                    uint32_t result = receiver_.GetMaxNonEmptyAddress(seg);
                    Respond(buffer, result);
                    break;
                }

                case Lizard1Message::SearchMemory:
                {
                    LAddress1 start;
                    uint32_t length;
                    std::vector<uint8_t> pattern;
                    uint32_t advance;
                    start.Serdes("start", sr);
                    sr.UInt32("length", length);
                    sr.Bytes("pattern", pattern);
                    sr.UInt32("advance", advance);
                    std::vector<LAddress1> result = receiver_.SearchMemory(start, length, pattern, advance);
                    Respond(buffer, result);
                    break;
                }

                case Lizard1Message::Disassemble:
                {
                    LAddress1 address;
                    uint32_t length;
                    address.Serdes("address", sr);
                    sr.UInt32("length", length);
                    std::vector<LAssemblyLine1> result = receiver_.Disassemble(address, length);
                    Respond(buffer, result);
                    break;
                }

                case Lizard1Message::GetMemory:
                {
                    LAddress1 address;
                    uint32_t length;
                    address.Serdes("address", sr);
                    sr.UInt32("length", length);
                    std::vector<uint8_t> result = receiver_.GetMemory(address, length);
                    Respond(buffer, result);
                    break;
                }

                case Lizard1Message::SetMemory:
                {
                    LAddress1 address;
                    std::vector<uint8_t> bytes;
                    address.Serdes("address", sr);
                    sr.Bytes("bytes", bytes);
                    receiver_.SetMemory(address, bytes);
                    Respond(buffer);
                    break;
                }

                case Lizard1Message::ListBreakpoints:
                {
                    std::vector<LBreakpoint1> result = receiver_.ListBreakpoints();
                    Respond(buffer, result);
                    break;
                }

                case Lizard1Message::SetBreakpoint:
                {
                    LBreakpoint1 breakpoint;
                    breakpoint.Serdes("breakpoint", sr);
                    receiver_.SetBreakpoint(breakpoint);
                    Respond(buffer);
                    break;
                }

                case Lizard1Message::EnableBreakpoint:
                {
                    uint32_t id;
                    bool is_enabled;
                    sr.UInt32("id", id);
                    sr.Bool("is_enabled", is_enabled);
                    receiver_.EnableBreakpoint(id, is_enabled);
                    Respond(buffer);
                    break;
                }

                case Lizard1Message::DeleteBreakpoint:
                {
                    uint32_t id;
                    sr.UInt32("id", id);
                    receiver_.DeleteBreakpoint(id);
                    Respond(buffer);
                    break;
                }

                case Lizard1Message::SetRegister:
                {
                    LRegister1 reg;
                    uint32_t value;
                    sr.UInt8Enum("reg", reg);
                    sr.UInt32("value", value);
                    receiver_.SetRegister(reg, value);
                    Respond(buffer);
                    break;
                }

                case Lizard1Message::GetGdt:
                {
                    std::vector<LDescriptor1> result = receiver_.GetGdt();
                    Respond(buffer, result);
                    break;
                }

                case Lizard1Message::GetLdt:
                {
                    std::vector<LDescriptor1> result = receiver_.GetLdt();
                    Respond(buffer, result);
                    break;
                }
            }

#ifdef _DEBUG
            if (sr.BytesRemaining() != 0)
                throw CommsError("Unexpected data remaining after processing Lizard1 message");
#endif
        }
    };

    IDeserializer* MakeLizard1Deserializer(ILizard1& receiver) { return new Lizard1Deserializer(receiver); }

    class Lizard1Serializer final : public ILizard1, BaseSerializer
    {
    public:
        explicit Lizard1Serializer(std::function<void(std::vector<uint8_t>&)> sendCallback)
            : BaseSerializer(std::move(sendCallback))
        {
        }

        void Continue() override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::Continue;

            sw.UInt16Enum("type", type);
            sendCallback_(buffer);
        }

        LRegisters1 Break() override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::Break;

            sw.UInt16Enum("type", type);
            sendCallback_(buffer);
            return DecodeResponse<LRegisters1>(buffer);
        }

        LRegisters1 StepIn() override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::StepIn;

            sw.UInt16Enum("type", type);
            sendCallback_(buffer);
            return DecodeResponse<LRegisters1>(buffer);
        }

        LRegisters1 StepOver() override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::StepOver;

            sw.UInt16Enum("type", type);
            sendCallback_(buffer);
            return DecodeResponse<LRegisters1>(buffer);
        }

        LRegisters1 StepOut() override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::StepOut;

            sw.UInt16Enum("type", type);
            sendCallback_(buffer);
            return DecodeResponse<LRegisters1>(buffer);
        }

        LRegisters1 StepMultiple(uint32_t cycles) override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::StepMultiple;

            sw.UInt16Enum("type", type);
            sw.UInt32("cycles", cycles);
            sendCallback_(buffer);
            return DecodeResponse<LRegisters1>(buffer);
        }

        void RunToAddress(LAddress1& address) override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::RunToAddress;

            sw.UInt16Enum("type", type);
            address.Serdes("address", sw);
            sendCallback_(buffer);
        }

        LRegisters1 GetState() override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::GetState;

            sw.UInt16Enum("type", type);
            sendCallback_(buffer);
            return DecodeResponse<LRegisters1>(buffer);
        }

        uint32_t GetMaxNonEmptyAddress(uint16_t seg) override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::GetMaxNonEmptyAddress;

            sw.UInt16Enum("type", type);
            sw.UInt16("seg", seg);
            sendCallback_(buffer);
            return DecodeResponse<uint32_t>(buffer);
        }

        std::vector<LAddress1> SearchMemory(LAddress1& start, uint32_t length, std::vector<uint8_t>& pattern, uint32_t advance) override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::SearchMemory;

            sw.UInt16Enum("type", type);
            start.Serdes("start", sw);
            sw.UInt32("length", length);
            sw.Bytes("pattern", pattern);
            sw.UInt32("advance", advance);
            sendCallback_(buffer);
            return DecodeListResponse<LAddress1>(buffer);
        }

        std::vector<LAssemblyLine1> Disassemble(LAddress1& address, uint32_t length) override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::Disassemble;

            sw.UInt16Enum("type", type);
            address.Serdes("address", sw);
            sw.UInt32("length", length);
            sendCallback_(buffer);
            return DecodeListResponse<LAssemblyLine1>(buffer);
        }

        std::vector<uint8_t> GetMemory(LAddress1& address, uint32_t length) override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::GetMemory;

            sw.UInt16Enum("type", type);
            address.Serdes("address", sw);
            sw.UInt32("length", length);
            sendCallback_(buffer);
            return buffer;
        }

        void SetMemory(LAddress1& address, std::vector<uint8_t>& bytes) override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::SetMemory;

            sw.UInt16Enum("type", type);
            address.Serdes("address", sw);
            sw.Bytes("bytes", bytes);
            sendCallback_(buffer);
        }

        std::vector<LBreakpoint1> ListBreakpoints() override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::ListBreakpoints;

            sw.UInt16Enum("type", type);
            sendCallback_(buffer);
            return DecodeListResponse<LBreakpoint1>(buffer);
        }

        void SetBreakpoint(LBreakpoint1& breakpoint) override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::SetBreakpoint;

            sw.UInt16Enum("type", type);
            breakpoint.Serdes("breakpoint", sw);
            sendCallback_(buffer);
        }

        void EnableBreakpoint(uint32_t id, bool is_enabled) override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::EnableBreakpoint;

            sw.UInt16Enum("type", type);
            sw.UInt32("id", id);
            sw.Bool("is_enabled", is_enabled);
            sendCallback_(buffer);
        }

        void DeleteBreakpoint(uint32_t id) override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::DeleteBreakpoint;

            sw.UInt16Enum("type", type);
            sw.UInt32("id", id);
            sendCallback_(buffer);
        }

        void SetRegister(LRegister1 reg, uint32_t value) override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::SetRegister;

            sw.UInt16Enum("type", type);
            sw.UInt8Enum("reg", reg);
            sw.UInt32("value", value);
            sendCallback_(buffer);
        }

        std::vector<LDescriptor1> GetGdt() override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::GetGdt;

            sw.UInt16Enum("type", type);
            sendCallback_(buffer);
            return DecodeListResponse<LDescriptor1>(buffer);
        }

        std::vector<LDescriptor1> GetLdt() override
        {
            std::vector<uint8_t> buffer;
            SerdesWrite sw(buffer);
            Lizard1Message type = Lizard1Message::GetLdt;

            sw.UInt16Enum("type", type);
            sendCallback_(buffer);
            return DecodeListResponse<LDescriptor1>(buffer);
        }
    };

    ILizard1* MakeLizard1Serializer(std::function<void(std::vector<uint8_t>&)> sendCallback)
    {
        return new Lizard1Serializer(std::move(sendCallback));
    }

}